version: "3.9"
services:
    phonebook-herman-node:
        build:
            context: docker/development/node
        environment:
            WDS_SOCKET_PORT: 0
            NODE_ENV: development
            REACT_APP_API_URL: http://api.localhost/api/v1/
        volumes:
            - ./:/app:rw
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn dev"
        tty: true
        networks:
            - traefik-public

    phonebook-herman-node-cli:
        build:
            context: docker/development/node
        volumes:
            - ./:/app
        networks:
            - traefik-public

    phonebook-herman-front:
        build:
            context: docker/development/nginx
        networks:
            - traefik-public
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.herman-phonebook.entrypoints=http
            - traefik.http.routers.herman-phonebook.rule=Host(`herman.pb.localhost`) || Host(`herman.phonebook.localhost`)
            - traefik.http.services.herman-phonebook.loadBalancer.server.port=80

networks:
    traefik-public:
        external: true